### @name="GET all Vehicles"
GET http://localhost:8080/api/vehicles
Accept: application/json

### @name="add a Vehicle"
POST http://localhost:8080/api/vehicles
Accept: application/json
Content-Type: application/json

{
  "registrationNumber": "AP-09-AA-1111",
  "fuelType": "DIESEL",
  "dailyHireRate": 3500.00
}